services:
  tasks_db:
    container_name: tasks_db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ronaldaodb
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: {}
